### ISSUE TITLE
SVG content is not centered/correctly panned when scale is < 1

### ISSUE THREAD

**Issue by paopre** [luncheon/svg-pan-zoom-select#3]
Hello.

As you can see in this jsfiddle:

https://jsfiddle.net/pLhb419u/

... when the scale amount is < 1, the svg is resized in the left top corner. Is there a way to fix this (or at least a work around) so to see the picture resized at the mouse position or at least centered?

Thanks for your great work!

**Comment by luncheon** [comment]
Thank you. You're right. I will try to fix it.

**Comment by luncheon** [comment]
v0.3.0 has been released to fix this bug. Please give it a try.

**Comment by paopre** [comment]
Hello. Doesn't work yet in this way: when scale is < 1 you can't pan the drawing. 
Check this:

https://jsfiddle.net/rqcn8vo5/1/

Also: I suggest you to add borders in your examples, both in the drawing and in the container. Otherwise it's impossible to figure what's happening.
Also: I suggest you to have a look at this:

https://github.com/timmywil/panzoom

with the 'overflow' property set, which creates scrollbars. It will help you in understanding how to manage the discussed case

**Comment by luncheon** [comment]
OK, panning is implemented when scale < 1 on v0.4.0. Thank you.
