### ISSUE TITLE
Support for different keys for data-pan-on-drag

### ISSUE THREAD

**Issue by Korak-997** [luncheon/svg-pan-zoom-select#7]
FIrst of all Thanks so much for that lovely tool. 

I was wondering if somehow Support for different keys for **data-pan-on-drag** can be added ?!

In my project i kind of need usage of left click , so it will be easier for me if for example the function works when i push for example **CTRL + L-CLICK** . Or maybe another combinations !!

Can something like that be added ?

**Comment by luncheon** [comment]
OK. Wait a moment.

**Comment by luncheon** [comment]
`data-pan-on-drag="modifier: Control"` (`Alt` | `Shift` | `Meta`) has been implemented in v0.5.1. Please try it out.
Thank you for your suggestion!

**Comment by Korak-997** [comment]
@luncheon ohhh thanks a lot for that quick review and solution :) i will check it out and test it for sure. But while it is used in a project at work ,so now i do not have access to at untill monday. on monday i will check it out and give you my feed back for sure. 
Again thanks so much for that quick answer.

**Comment by Korak-997** [comment]
@luncheon am not Sure if the Feature is working properly !!!
i tested with **Alt, Shift and Control** , but it seems it is not working !

I am still able to drag and move the element with only Holding Click !

Here is a pic of my code Snippet , maybe i am doing it in a wrong way ?

![Screenshot from 2021-04-19 08-37-49](https://user-images.githubusercontent.com/59537065/115192341-f77eb600-a0ea-11eb-9b2c-4a8aa2198a3b.png)


The point is i want the user to be able to drag the element only when he/she holds  **KEY + CLICK** together at same time .

**Comment by luncheon** [comment]
Please use the capitalized `modifier: Control` instead of `modifier: control`.
I know this looks awkward, but it is in line with the `getModifierState()` API.
https://developer.mozilla.org/docs/Web/API/KeyboardEvent/getModifierState

**Comment by Korak-997** [comment]
@luncheon i used Capitalized `modifier: Control` still does not seem like working .

**Comment by luncheon** [comment]
This is a smallest example. Doesn't this work?
https://codepen.io/luncheon/pen/WNRgExW

**Comment by Korak-997** [comment]
@luncheon it actually does work that way . I think maybe the installation causes that bug in my code ! 

I will remove and reinstall it again and see what happens . Maybe that way the package gets updated .

**Comment by Korak-997** [comment]
@luncheon it worked :+1:  perfectly , the problem was i needed to update the Package. 
Again thanks a lot for your kind responses and solutions , also am so sorry if i bothered you in anyway .

Close the Issue also :smiley: 

Again thanks so much.
